
export const MISSION_STATUSES = {
    CREATED: 'CREATED',
    READY: 'READY',
    IN_PROGRESS: 'IN_PROGRESS',
    PAUSED: 'PAUSED',
    COMPLETED: 'COMPLETED',
    ABORTED: 'ABORTED',
} as const;


export const DRONE_STATUSES = {
    AVAILABLE: 'AVAILABLE',
    IN_MISSION: 'IN_MISSION',
    OFFLINE: 'OFFLINE',
} as const;


export const MISSION_PATTERNS = {
    GRID: 'GRID',
    CROSSHATCH: 'CROSSHATCH',
    PERIMETER: 'PERIMETER',
} as const;


export const ABORT_REASONS = {
    LOW_BATTERY: 'LOW_BATTERY',
    OPERATOR_ABORT: 'OPERATOR_ABORT',
    SYSTEM_ERROR: 'SYSTEM_ERROR',
} as const;


export const TELEMETRY_EVENTS = {
    SUBSCRIBE_MISSION: 'SUBSCRIBE_MISSION',
    UNSUBSCRIBE_MISSION: 'UNSUBSCRIBE_MISSION',
    SUBSCRIBE_ACTIVE_MISSIONS: 'SUBSCRIBE_ACTIVE_MISSIONS',
    TELEMETRY_UPDATE: 'TELEMETRY_UPDATE',
    HEARTBEAT: 'HEARTBEAT',
    MISSION_COMPLETED: 'MISSION_COMPLETED',
    MISSION_STATUS_UPDATE: 'MISSION_STATUS_UPDATE',
} as const;


export const MISSION_EVENT_TYPES = {
    MISSION_CREATED: 'MISSION_CREATED',
    DRONE_ASSIGNED: 'DRONE_ASSIGNED',
    MISSION_STARTED: 'MISSION_STARTED',
    MISSION_PAUSED: 'MISSION_PAUSED',
    MISSION_RESUMED: 'MISSION_RESUMED',
    MISSION_COMPLETED: 'MISSION_COMPLETED',
    MISSION_ABORTED: 'MISSION_ABORTED',
} as const;


export const DEFAULTS = {
    BATTERY_THRESHOLD: 20,
    MIN_ALTITUDE: 10,
    MAX_ALTITUDE: 400,
    DEFAULT_SPEED: 5,
    DEFAULT_OVERLAP: 70,
} as const;


export const PAGINATION = {
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
} as const;
